"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, <FULL NAME> and <FULL NAME>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1:
UT EID 2:
"""


def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    rails = [[] for _ in range(key)]
    direction = 1
    row = 0
    
    for char in string:
        rails[row].append(char)
        
        if row == 0:
            direction = 1
        elif row == key - 1:
            direction = -1
        
        row += direction
    
    result = ""
    for rail in rails:
        result += "".join(rail)
    
    return result


def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    rails = [[''] * len(string) for _ in range(key)]
    
    direction = 1
    row = 0
    for col in range(len(string)):
        rails[row][col] = '*'
        
        if row == 0:
            direction = 1
        elif row == key - 1:
            direction = -1
        
        row += direction
    
    index = 0
    for i in range(key):
        for j in range(len(string)):
            if rails[i][j] == '*' and index < len(string):
                rails[i][j] = string[index]
                index += 1
    
    result = ""
    direction = 1
    row = 0
    for col in range(len(string)):
        result += rails[row][col]
        
        if row == 0:
            direction = 1
        elif row == key - 1:
            direction = -1
        
        row += direction
    
    return result


def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    string = string.lower()
    
    result = ""
    for char in string:
        if 'a' <= char <= 'z':
            result += char
    
    return result


def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    p_val = ord(p) - ord('a')
    s_val = ord(s) - ord('a')
    
    encoded_val = (s_val + p_val) % 26
    
    return chr(encoded_val + ord('a'))


def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    p_val = ord(p) - ord('a')
    s_val = ord(s) - ord('a')
    
    decoded_val = (s_val - p_val + 26) % 26
    
    return chr(decoded_val + ord('a'))


def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    filtered_string = filter_string(string)
    filtered_phrase = filter_string(phrase)
    
    result = ""
    
    for i in range(len(filtered_string)):
        p = filtered_phrase[i % len(filtered_phrase)]
        s = filtered_string[i]
        
        result += encode_character(p, s)
    
    return result


def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    filtered_phrase = filter_string(phrase)
    
    result = ""
    
    for i in range(len(string)):
        p = filtered_phrase[i % len(filtered_phrase)]
        s = string[i]
        
        result += decode_character(p, s)
    
    return result

# TODO: implement this function. You may delete this comment after you are done.
def main():
    """Main function that reads stdin and runs each cipher"""
    # read the plain text from stdin (terminal/input)

    # read the key from stdin (terminal/input)

    # encrypt and print the encoded text using rail fence cipher

    # read encoded text from stdin (terminal/input)

    # read the key from stdin (terminal/input)

    # decrypt and print the plain text using rail fence cipher

    # read the plain text from stdin (terminal/input)

    # read the pass phrase from stdin (terminal/input)

    # encrypt and print the encoded text using Vigenere cipher

    # read the encoded text from stdin (terminal/input)

    # read the pass phrase from stdin (terminal/input)

    # decrypt and print the plain text using Vigenere cipher


# Do NOT modify the following code.
if __name__ == "__main__":
    main()
